# Generated by Django 5.1.4 on 2025-01-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
