# Generated by Django 5.1.4 on 2025-01-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_category_options_review_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reviews.category'),
            preserve_default=False,
        ),
    ]
