# Generated by Django 5.1.4 on 2025-01-16 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.category'),
        ),
    ]
