# Generated by Django 5.1.4 on 2025-01-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_reviewvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
