# Generated by Django 5.1.5 on 2025-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamescore_delete_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('Math Facts', 'MATH'), ('Anagram Hunt', 'ANAGRAM')], default='MATH'),
        ),
    ]
